pub(crate) mod basic;
pub(crate) mod boolean;
mod declare_empty_get_input_ids;
pub(crate) mod declare_empty_update;
pub(crate) mod declare_input_ids;
mod declare_input_ids_and_its_getter;
pub(crate) mod declare_update;
pub(crate) mod filter;
pub(crate) mod math;
pub(crate) mod module;
pub(crate) mod random;
pub(crate) mod wave;
